/* tslint:disable */
/* eslint-disable */
/**
 * LIS.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonModel
 */
export interface PersonModel {
    /**
     * 
     * @type {string}
     * @memberof PersonModel
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof PersonModel
     */
    'age'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PersonModel
     */
    'hometown'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonModel
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonModel
     */
    'title': string | null;
}

